### ISSUE TITLE
Add Ability to Not trim() When Removing  Emojis

### ISSUE THREAD

**Issue by CodeMelted** [buckthorndev/remove-emoji#2]
Currently there are use cases where the ability to leave beginning and trailing whitespaces are needed.  Add a capability to not perform the trim capability.

**Comment by CodeMelted** [comment]
https://github.com/CodeMelted/remove-emoji/tree/ability_to_not_trim_when_removing_emojis  

The above is a fork and an example.  Hope this helps.

**Comment by n4ze3m** [comment]
https://github.com/buckthorndev/remove-emoji/tree/0.0.6 done <3
